#### 1.Найти фичи которые использует компания
#### 2. Создать модель которая предсказывает продажи
#### 3. Разбить датасет на обучающиеся и тренировочные данные
#### 4. Подсчитать среднеквадратичную ошибку MSE

#### Import Data:

In [2]:
#Import required libraries
import pandas as pd

In [3]:
df = pd.read_csv("Advertising+Budget+and+Sales.csv")

In [6]:
df

,Unnamed: 0,TV Ad Budget ($),Radio Ad Budget ($),Newspaper Ad Budget ($),Sales ($)
0,1,230.1,37.8,69.2,22.1
1,2,44.5,39.3,45.1,10.4
2,3,17.2,45.9,69.3,9.3
3,4,151.5,41.3,58.5,18.5
4,5,180.8,10.8,58.4,12.9
...,...,...,...,...,...
195,196,38.2,3.7,13.8,7.6
196,197,94.2,4.9,8.1,9.7
197,198,177.0,9.3,6.4,12.8
198,199,283.6,42.0,66.2,25.5
199,200,232.1,8.6,8.7,13.4

In [11]:
df[(df['Sales ($)'] > 22) & (df['TV Ad Budget ($)'] > 250) ]

,Unnamed: 0,TV Ad Budget ($),Radio Ad Budget ($),Newspaper Ad Budget ($),Sales ($)
17,18,281.4,39.6,55.8,24.4
36,37,266.9,43.8,5.0,25.4
61,62,261.3,42.7,54.7,24.2
93,94,250.9,36.5,72.3,22.2
98,99,289.7,42.3,51.2,25.4
101,102,296.4,36.3,100.9,23.8
175,176,276.9,48.9,41.8,27.0
183,184,287.6,43.0,71.8,26.2
198,199,283.6,42.0,66.2,25.5

In [14]:
df.loc[10:14, 'TV Ad Budget ($)': 'Newspaper Ad Budget ($)']

    TV Ad Budget ($)  Radio Ad Budget ($)  Newspaper Ad Budget ($)
10              66.1                  5.8                     24.2
11             214.7                 24.0                      4.0
12              23.8                 35.1                     65.9
13              97.5                  7.6                      7.2
14             204.1                 32.9                     46.0

In [16]:
#show indexes start = 0 , stop = 200 step = 1
df.index

RangeIndex(start=0, stop=200, step=1)

In [17]:
#show columns on dataset
df.columns

Index(['Unnamed: 0', 'TV Ad Budget ($)', 'Radio Ad Budget ($)',
       'Newspaper Ad Budget ($)', 'Sales ($)'],
      dtype='object')

In [19]:
df_mod = pd.read_csv("Advertising+Budget+and+Sales.csv", index_col=0)

In [20]:
df_mod

     TV Ad Budget ($)  Radio Ad Budget ($)  Newspaper Ad Budget ($)  Sales ($)
1               230.1                 37.8                     69.2       22.1
2                44.5                 39.3                     45.1       10.4
3                17.2                 45.9                     69.3        9.3
4               151.5                 41.3                     58.5       18.5
5               180.8                 10.8                     58.4       12.9
..                ...                  ...                      ...        ...
196              38.2                  3.7                     13.8        7.6
197              94.2                  4.9                      8.1        9.7
198             177.0                  9.3                      6.4       12.8
199             283.6                 42.0                     66.2       25.5
200             232.1                  8.6                      8.7       13.4

[200 rows x 4 columns]

#### Analyze dataset

In [21]:
df_mod.head(10)

    TV Ad Budget ($)  Radio Ad Budget ($)  Newspaper Ad Budget ($)  Sales ($)
1              230.1                 37.8                     69.2       22.1
2               44.5                 39.3                     45.1       10.4
3               17.2                 45.9                     69.3        9.3
4              151.5                 41.3                     58.5       18.5
5              180.8                 10.8                     58.4       12.9
6                8.7                 48.9                     75.0        7.2
7               57.5                 32.8                     23.5       11.8
8              120.2                 19.6                     11.6       13.2
9                8.6                  2.1                      1.0        4.8
10             199.8                  2.6                     21.2       10.6

In [22]:
df_mod.size

800

# Find the features of media

In [25]:
#200 rows and 4 columns
df_mod.shape
df_mod.columns

Index(['TV Ad Budget ($)', 'Radio Ad Budget ($)', 'Newspaper Ad Budget ($)',
       'Sales ($)'],
      dtype='object')

### Create to model and testing

In [28]:
x_features = df_mod[['TV Ad Budget ($)', 'Radio Ad Budget ($)', 'Newspaper Ad Budget ($)']]

In [29]:
x_features.head()

   TV Ad Budget ($)  Radio Ad Budget ($)  Newspaper Ad Budget ($)
1             230.1                 37.8                     69.2
2              44.5                 39.3                     45.1
3              17.2                 45.9                     69.3
4             151.5                 41.3                     58.5
5             180.8                 10.8                     58.4

In [30]:
#Create a target object
y_target = df_mod[['Sales ($)']]

In [31]:
y_target.head()

   Sales ($)
1       22.1
2       10.4
3        9.3
4       18.5
5       12.9

In [32]:
x_features.shape

(200, 3)

In [33]:
y_target.shape

(200, 1)

#### Split dataset on traning and test data

In [34]:
from sklearn.model_selection import train_test_split

In [59]:
x_train, x_test, y_train, y_test = train_test_split(x_features, y_target, random_state=27)

In [38]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(150, 3) (50, 3) (150, 1) (50, 1)

# Create a linear regression  model

In [39]:
from sklearn.linear_model import LinearRegression

In [40]:
linreg = LinearRegression()

In [53]:
linreg.fit(x_train, y_train)

LinearRegression()

In [54]:
print(linreg.intercept_)

[2.79916791]

In [55]:
print(linreg.coef_)

[[0.04648022 0.1845547  0.00286741]]

In [56]:
y_pred = linreg.predict(x_test)

In [57]:
y_pred

array([[14.75846783],
       [16.41852084],
       [16.41759144],
       [12.03709252],
       [20.70723013],
       [17.29565452],
       [14.96988622],
       [19.65050706],
       [23.56456091],
       [11.97347741],
       [19.50018553],
       [12.76087618],
       [10.57222916],
       [18.94036675],
       [ 8.59530013],
       [21.85921162],
       [12.62654629],
       [14.56942078],
       [ 9.97244579],
       [16.37300148],
       [15.78422833],
       [13.0595913 ],
       [14.24547458],
       [17.10679479],
       [18.06357979],
       [10.40616358],
       [ 9.69680278],
       [10.48598218],
       [16.34460782],
       [11.46674105],
       [10.58161139],
       [ 8.17350495],
       [ 9.10425404],
       [ 7.90763047],
       [23.2733627 ],
       [ 4.44591202],
       [ 4.43201673],
       [ 9.83072166],
       [12.90035894],
       [13.42658867],
       [15.33659361],
       [19.64025587],
       [ 7.72524213],
       [15.61866872],
       [17.98812442],
       [13.69839908],
       [ 6.54033781],
       [10.97508723],
       [ 5.29713478],
       [ 5.1469155 ]])

In [46]:
y_test

     Sales ($)
104       14.7
49        14.8
41        16.6
149       10.9
186       22.6
75        17.0
163       14.9
110       19.8
102       23.8
174       11.7
140       20.7
198       12.8
13         9.2
69        18.9
79         5.3
59        23.8
10        10.6
166       11.9
91        11.2
96        16.9
132       12.7
64        14.0
161       14.4
28        15.9
60        18.4
95        11.5
146       10.3
127        6.6
195       17.3
87        12.0
181       10.5
50         9.7
126       10.6
130        9.7
148       25.4
193        5.9
77         6.9
39        10.1
116       12.6
168       12.2
157       15.3
125       19.7
66         9.3
88        16.0
170       15.0
123       11.6
118        9.4
165       11.9
196        7.6
156        3.2

# Score MSE

In [50]:
from sklearn import metrics
import numpy as np

In [60]:
#Calculate MSE
print(metrics.mean_squared_error(y_test, y_pred))

2.4972996158775893

In [61]:
#Calculate RMSE
print(metrics.root_mean_squared_error(y_test, y_pred))

1.580284662925509

In [64]:
# NUMPY version RMSE
print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

1.580284662925509